DATA:
  IMG_SIZE: 448
MODEL:
  TYPE: swin
  NAME: ditask_base_448_r64
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 7
  DITASK:
    ENABLED: True
    R: [128, 128, 128, 128]
    SHARED_SCALE: [1.0]
    TASK_SCALE: [1.0]
    DROPOUT: [0.05, 0.05, 0.05, 0.05]
    TRAINABLE_SCALE_SHARED: False
    TRAINABLE_SCALE_PER_TASK: False
    INTERMEDIATE_SPECIALIZATION: False
    FREEZE_PRETRAINED: True
    SPLIT_QKV: False
    QKV_ENABLED: True
    PROJ_ENABLED: True
    FC1_ENABLED: True
    FC2_ENABLED: True
    DOWNSAMPLER_ENABLED: False
    R_PER_TASK:
      semseg: [64]
      normals: [64]
      sal: [64]
      human_parts: [64]
      edge: [64]
      depth: [64]
      shared: [128]
  DECODER_HEAD:
    semseg: hrnet
    normals: hrnet
    sal: hrnet
    human_parts: hrnet
    edge: hrnet
    depth: hrnet
